"use client";

import { Suspense, useEffect, useState } from "react";
import { useSearchParams }               from "next/navigation";
import Link                              from "next/link";

type Status = "loading" | "success" | "already_verified" | "error";

function VerifyContent() {
  const searchParams      = useSearchParams();
  const token             = searchParams.get("token");
  const email             = searchParams.get("email"); // present in links generated by register/resend
  const [status, setStatus]   = useState<Status>("loading");
  const [message, setMessage] = useState("");

  useEffect(() => {
    if (!token) {
      setStatus("error");
      setMessage("No verification token was provided. Please use the link from your email.");
      return;
    }

    // Build URL — include email when available so the API can distinguish
    // "already verified" from a truly invalid token.
    const url = new URL("/api/auth/verify", window.location.origin);
    url.searchParams.set("token", token);
    if (email) url.searchParams.set("email", email);

    fetch(url.toString())
      .then((r) => r.json())
      .then((d) => {
        if (d.alreadyVerified) {
          setStatus("already_verified");
        } else if (d.error) {
          setStatus("error");
          setMessage(d.error);
        } else {
          setStatus("success");
        }
      })
      .catch(() => {
        setStatus("error");
        setMessage("Something went wrong. Please try again or contact support.");
      });
  }, [token, email]);

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="w-full max-w-md">

        {/* Logo */}
        <div className="text-center mb-8">
          <Link
            href="/"
            className="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-primary-600 shadow-lg mb-4 hover:opacity-90 transition-all"
          >
            <svg className="w-8 h-8 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
            </svg>
          </Link>
          <h1 className="text-3xl font-bold text-gray-900">Nepal CRM</h1>
        </div>

        <div className="bg-white rounded-2xl shadow-xl border border-gray-100 p-8 text-center">

          {/* ── Checking ──────────────────────────────── */}
          {status === "loading" && (
            <>
              <div className="flex justify-center mb-4">
                <div className="animate-spin w-10 h-10 border-4 border-primary-500 border-t-transparent rounded-full" />
              </div>
              <p className="text-gray-600">Verifying your email…</p>
            </>
          )}

          {/* ── Just verified ─────────────────────────── */}
          {status === "success" && (
            <>
              <div className="flex justify-center mb-4">
                <div className="w-16 h-16 rounded-full bg-green-100 flex items-center justify-center">
                  <svg className="w-8 h-8 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                  </svg>
                </div>
              </div>
              <h2 className="text-xl font-semibold text-gray-900 mb-2">Email verified!</h2>
              <p className="text-gray-500 mb-6">Your account is now active. You can sign in.</p>
              <Link
                href="/login"
                className="inline-flex items-center justify-center w-full py-2.5 px-4 bg-primary-600 hover:bg-primary-700 text-white font-semibold rounded-lg transition text-sm"
              >
                Go to Sign In
              </Link>
            </>
          )}

          {/* ── Already verified (old/reused link) ────── */}
          {status === "already_verified" && (
            <>
              <div className="flex justify-center mb-4">
                <div className="w-16 h-16 rounded-full bg-blue-100 flex items-center justify-center">
                  <svg className="w-8 h-8 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>
              </div>
              <h2 className="text-xl font-semibold text-gray-900 mb-2">Already verified</h2>
              <p className="text-gray-500 text-sm mb-6">
                This email has already been verified. You can sign in to your account.
              </p>
              <Link
                href="/login"
                className="inline-flex items-center justify-center w-full py-2.5 px-4 bg-primary-600 hover:bg-primary-700 text-white font-semibold rounded-lg transition text-sm"
              >
                Go to Sign In
              </Link>
            </>
          )}

          {/* ── Genuinely invalid token ────────────────── */}
          {status === "error" && (
            <>
              <div className="flex justify-center mb-4">
                <div className="w-16 h-16 rounded-full bg-red-100 flex items-center justify-center">
                  <svg className="w-8 h-8 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </div>
              </div>
              <h2 className="text-xl font-semibold text-gray-900 mb-2">Verification failed</h2>
              <p className="text-gray-500 text-sm mb-6">{message}</p>
              <Link
                href="/login"
                className="text-sm text-primary-600 hover:underline"
              >
                Back to Sign In
              </Link>
            </>
          )}

        </div>
      </div>
    </div>
  );
}

export default function VerifyPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen flex items-center justify-center">
          <div className="animate-spin w-8 h-8 border-4 border-primary-500 border-t-transparent rounded-full" />
        </div>
      }
    >
      <VerifyContent />
    </Suspense>
  );
}
